#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Apr 13 18:22:17 CEST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=
enableShaders=true
